### ISSUE TITLE
Accessor for Lockscreen wallpaper?

### ISSUE THREAD

**Issue by nhantrn** [Ciantic/VirtualDesktopAccessor#13]
This is perhaps off topic, but is there a way to access the wallpaper for the lock screen/login screen in Windows 10? I would like to change the lockscreen wallpaper after every login using a schedule task.

**Comment by Ciantic** [comment]
It's a bit off-topic, digging to the undocumented Windows COM interfaces is a bit tedious task. 

I haven't yet found a good tool that would discover hidden COM interfaces automatically. Right now the process requires 1. to get a pointer to interface, 2. to inspect the pointer vtable in the memory and iterating the parameters. 

Such a tool would be a great though, since that lock-screen most certainly does have hidden API, however I don't have time to investigate this.

**Comment by mzomparelli** [comment]
I use `OleViewDotNet` to identify COM interfaces.

**Comment by Ciantic** [comment]
@mzomparelli oh wow, thanks a lot! I have to look at that.

**Comment by Ciantic** [comment]
Btw, the OleViewDotNet tool is so great, that I probably found (for fun) the interface for that Lock Screen image. 

I have no interest to look on this further though, but if someone else is, using that tool one finds this gem at *ActXPrxy.dll*:

```
[Guid("7093134e-768e-47b0-ace0-b2ccd7124ec6")]
interface IAuthLockScreenImageEx : IUnknown {
    HRESULT Proc3(/* Stack Offset: 8 */ [In] /* unique */wchar_t* p0, /* Stack Offset: 16 */ [In] int p1, /* Stack Offset: 24 */ [In] int p2, /* Stack Offset: 32 */ [In] /* ENUM32 */ int p3, /* Stack Offset: 40 */ [Out] IUnknown** p4);
}
```

Now, using that to do that is another thing entirely. One would probably have to debug the process that lockscreen is using and put a break point on process loading *ActXPrxy.dll* and go from there.
