### ISSUE TITLE
Stop working on windows 10 build 20231

### ISSUE THREAD

**Issue by hadimostafapour** [Ciantic/VirtualDesktopAccessor#33]
Dll does not work anymore after upgrading to build 20231

**Comment by anaisbetts** [comment]
Yep, all the interfaces GUIDs change again in this build, and it appears that they actually changed the underlying interfaces too. Any tips on how to reverse-engineer the new ones?

**Comment by Ciantic** [comment]
Is that build a 21H1? I think I have to test with it when I get it, I'm not running insider builds.

I don't know how to reverse engineer the interfaces, but we can get the interface *definitions* with OleView, see this example screenshot: https://github.com/Ciantic/VirtualDesktopAccessor/issues/32#issuecomment-632620027 and also searching with new GUID's in Github will usually give other peoples fixes to them.

**Comment by mcflythekid** [comment]
Still waiting for you @Ciantic because my app depends on your dll

**Comment by Ciantic** [comment]
I update when Windows 10 upgrades, and 20231 is 21H1 preview build so that update is coming in first half of next year.

There is no solution here unfortunately. I don't use insider builds, nor I do backwards compatibility with the DLL either, this is very rough implementation. It would be nice if Microsoft did stable API so this wouldn't break all the time.

**Comment by mzomparelli** [comment]
I have identified the changes to the interfaces. It's not perfect but it works. Let me know if you make it better by naming the unknown or fixing my mistakes. I think these are all the changes since 20H2. If I see another that has changed I will add it to the wiki.

https://github.com/mzomparelli/zVirtualDesktop/wiki

**Comment by letacio** [comment]
> I have identified the changes to the interfaces. It's not perfect but it works. Let me know if you make it better by naming the unknown or fixing my mistakes. I think these are all the changes since 20H2. If I see another that has changed I will add it to the wiki.
> 
> https://github.com/mzomparelli/zVirtualDesktop/wiki

Can you please explain me how to use this? I see the code but do not know how to correct the issue on my code with that!
Thanks a lot!
