### ISSUE TITLE
Rust: wrappers for creating and removing desktops

### ISSUE THREAD

**Issue by slavoutich** [Ciantic/VirtualDesktopAccessor#37]
Interfaces for creating and removing desktops are wrapped, but the crate provides no public functions to use them.

I have started implementing `create_desktop` in a [branch of a fork](https://github.com/slavoutich/VirtualDesktopAccessor/tree/desktop_manipulation), but I didn't figure out a way how to return a desktop created: I think that the function `create_desktop` in `lib.rs` must have signature `pub fn create_desktop() -> Result<Desktop, Error>` instead of `pub fn create_desktop() -> Result<(), Error>`. If you can help me on how to fix that, I can implement `create_desktop` and `remove_desktop`, write a test for them and open a PR.

**Comment by Ciantic** [comment]
Hmm, interesting. You might be only user of this library at the moment. I haven't had time to rewrite my DLL to work with this.

Now I did `create_desktop` however, not sure if it's buggy! My explorer.exe crashed but it did create desktop.

**Comment by Ciantic** [comment]
Hold on, I will implement the remove_desktop too.

**Comment by Ciantic** [comment]
Now there is both.

**Comment by Ciantic** [comment]
I did `create_desktop` and `remove_desktop`, pushed new version to crates 0.0.20.

There are some changes to come to this crate still, for instance the message passing works upside down. In Rust the message passing should work by giving a `Sender` instead of getting a `Reciever`. I might fix that when I come back to this, I have implemented it wrong way around first time.

**Comment by slavoutich** [comment]
Thanks a lot! FYI I use it to write a [library](https://gitlab.com/slavoutich/tileme) to bring Windows experience somehow closer to XMonad. I will test the updated version now.
