### ISSUE TITLE
Is 24H2 supported?

### ISSUE THREAD

**Issue by parfait8566** [Ciantic/VirtualDesktopAccessor#96]
Since 24H2 officially release, I'd like to know if it's supported before updating

**Comment by Lej77** [comment]
It likely isn't since there hasn't been an update for a while and 24H2 seems to require some changes, see [Win11 24H2 · Issue #26 · Slion/VirtualDesktop](https://github.com/Slion/VirtualDesktop/issues/26).

Edit: I read through the source code of the [linked commit](https://github.com/MScholtes/VirtualDesktop/commit/a3588845ffa5d8bf37daebf1c7810f17291c432f) and the only change I could find was the addition of the `SwitchDesktopAndMoveForegroundView` method to the `IVirtualDesktopManagerInternal` interface. All the interface ids seems to have remained the same.

**Comment by parfait8566** [comment]
Yeah, works fine on 24H2.
